import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": "الرئيسية",
          "2": "الفئات",
          "3": "الاعدادات",
          "4": "اللغة",
          "5": "المظهر",
          "6": "الانجليزية",
          "7": "عام",
          "8": "الإشعارات",
          "9": "الحساب",
          "10": "حساب شخصي",
          "11": "اخري",
          "12": "الخصوصية",
          "13": "حول البرنامج",
          "14": "المفضلة",
          "15": "الفئات",
          "16": "محادثة",
          "17": "بحث",
          "18": "تسجيل الدخول",
          "19": "تسجيل",
          "20": "العربية",
          "21": "تخطي",
          "22": "تم",
          "23": "الفلتر",
          "24": "التفاصيل",
          "25": "سعر التصميم",
          "26": "سعر الإنهاء",
          "27": "التكلفة +",
          "28": "عرض",
          "29": "رقم الهاتف",
          "30": "البريد الإلكتروني",
          "31": "تغيير كلمة السر",
          "32": "تسجيل الخروج",
          "33": "نوع الفئة",
          "34": "نوع النمط",
          "35": "الرجاء تحديد كل من الفئة والنمط",
          "36": "تطبيق",
          "37": "الإسم",
          "38": "من فضلك أدخل كل البيانات!",
          "39": "أدخل البيانات الجديدة",
          "40": "أسم المستخدم",
          "dark": "غامق",
          "light": "فاتح",
          "password updated successfully": "تم تغيير كلمة السر بنجاح",
          "Current Password": "كلمة المرور الحالية",
          "New Password": "كلمة المرور الجديدة",
          "password must be at least 6 characters":
              "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
          "please, verify current password ,try again later":
              "يرجى التحقق من كلمة المرور الحالية، ثم حاول مرة أخرى لاحقًا",
          "Loading...": "تحميل...",
          "Update": "تحديث",
          "Login to your account": "تسجيل الدخول إلى حسابك",
          "Please enter email!": "الرجاء إدخال البريد الإلكتروني!",
          "Please enter password!": "الرجاء إدخال كلمة المرور!",
          "Password": "كلمة المرور",
          "Don\'t have an account?": "ليس لديك حساب؟",
          "Sign up": "اشتراك",
          "Conitnue as a Guest": "الاستمرار كضيف",
          "Create your account": "أنشئ حسابك",
          "Please enter name!": "الرجاء إدخال الاسم!",
          "Please enter phone!": "الرجاء إدخال الهاتف!",
          "You Have To Sign In": "يجب عليك تسجيل الدخول",
          "Please go back to sign in to view the full details and interact.":
              "يرجى العودة لتسجيل الدخول لعرض التفاصيل الكاملة والتفاعل.",
          "OK": "حسنا",
          "Description": "الوصف",
          "Design Price": "سعر التصميم",
          "Discover The World Of Beauty": "اكتشف عالم الجمال",
          "Discover the world of beauty":
              "اكتشف عالم الجمال والإبداع مع صور شركتنا \nحيث تجتمع الأفكار الرائعة مع التصميم الاستثنائي",
          "Direct": "التواصل المباشر مع\n الشركة",
          "Direct communication with \nthe company through a chat":
              "التواصل المباشر مع الشركة من خلال الدردشة",
          "Super Offer": "عرض سوبر",
          "Get 60% off in our first booking":
              "احصل على خصم 60% عند حجزنا الأول",
          "Views": "مشاهدات",
          "Select Language": "اختر اللغة",
          "Our Mission": "مهمتنا",
          "Our mission is to provide the best services and products to our customers. We are committed to excellence and strive to exceed expectations in everything we do.":
              "مهمتنا هي تقديم أفضل الخدمات والمنتجات لعملائنا. نحن ملتزمون بالتميز ونسعى جاهدين لتجاوز التوقعات في كل ما نقوم به. ",
          "Our Team": "فريقنا",
          "We have a diverse and talented team of professionals who are passionate about what they do. Our team works tirelessly to deliver the best results for our clients.":
              "لدينا فريق متنوع وموهوب من المحترفين المتحمسين لما يفعلونه. يعمل فريقنا بلا كلل لتقديم أفضل النتائج لعملائنا.",
          "Contact Us": "اتصل بنا",
          "If you have any questions or would like to get in touch, please feel free to contact us at grand-deco-mm.com.":
              "إذا كانت لديك أي أسئلة أو ترغب في التواصل معنا، فلا تتردد في الاتصال بنا على grand-deco-mm.com.",
          "Select Theme": "اختر المظهر",
          "Unknown": "غير معروف",
          "User data updated successfully": "تم تغيير بيانات المستخدم بنجاح",
          "Fields cannot be empty": "لا يمكن أن تكون الحقول فارغة",
          "Password must be at least 6 characters":
              "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل"
        },
        "en": {
          "1": "Home",
          "2": "Category",
          "3": "Settings",
          "4": "Language",
          "5": "Theme",
          "6": "English",
          "7": "General",
          "8": "Notifications",
          "9": "Account",
          "10": "profile",
          "11": "Other",
          "12": "PrivacyPolicy",
          "13": "About Us",
          "14": "Favorite",
          "15": "Category",
          "16": "Chat",
          "17": "Search",
          "18": "Login",
          "19": "Register",
          "20": "Arabic",
          "21": "Skip",
          "22": "Done",
          "23": "Filter",
          "24": "Details",
          "25": "The Price Of Design",
          "26": "Finishing Price",
          "27": "Cost +",
          "28": "Offer",
          "29": "Phone Number",
          "30": "Email",
          "31": "Change password",
          "32": "log out",
          "33": "Type Of Category",
          "34": "Type Of Style",
          "35": "Please select both category and style",
          "36": "Apply",
          "37": "Name",
          "38": "Please enter all data!",
          "39": "Enter New Data",
          "40": "User Name",
          "dark1": "Dark",
          "light": "Light",
          "password updated successfully": "password updated successfully",
          "Current Password": "Current Password",
          "New Password": "New Password",
          "password must be at least 6 characters":
              "password must be at least 6 characters",
          "please, verify current password ,try again later":
              "please, verify current password ,try again later",
          "Loading...": "Loading...",
          "Update": "Update",
          "Login to your account": "Login to your account",
          "Please enter email!": "Please enter email!",
          "Please enter password!": "Please enter password!",
          "Password": "Password",
          "Don\'t have an account?": "Don\'t have an account?",
          "Sign up": "Sign up",
          "Conitnue as a Guest": "Conitnue as a Guest",
          "Create your account": "Create your account",
          "Please enter name!": "Please enter name!",
          "Please enter phone!": "Please enter phone!",
          "You Have To Sign In": "You Have To Sign In",
          "Please go back to sign in to view the full details and interact.":
              "Please go back to sign in to view the full details and interact.",
          "OK": "OK",
          "Description": "Description",
          "Design Price": "Design Price",
          "Discover The World Of Beauty": "Discover The World Of Beauty",
          "Discover the world of beauty":
              "Discover the world of beauty and creativity with our company’s images \nwhere wondrful ideas meet exceptional design",
          "Direct": "Direct communication with\n             the company",
          "Direct communication with \nthe company through a chat":
              "Direct communication with \nthe company through a chat",
          "Super Offer": "Super Offer",
          "Get 60% off in our first booking":
              "Get 60% off in our first booking",
          "Views": "Views",
          "Select Language": "Select Language",
          "Our Mission": "Our Mission",
          "Our mission is to provide the best services and products to our customers. We are committed to excellence and strive to exceed expectations in everything we do.":
              "Our mission is to provide the best services and products to our customers. We are committed to excellence and strive to exceed expectations in everything we do.",
          "Our Team": "Our Team",
          "We have a diverse and talented team of professionals who are passionate about what they do. Our team works tirelessly to deliver the best results for our clients.":
              "We have a diverse and talented team of professionals who are passionate about what they do. Our team works tirelessly to deliver the best results for our clients.",
          "Contact Us": "Contact Us",
          "If you have any questions or would like to get in touch, please feel free to contact us at grand-deco-mm.com.":
              "If you have any questions or would like to get in touch, please feel free to contact us at grand-deco-mm.com.",
          "Select Theme": "Select Theme",
          "Unknown": "Unknown",
          "User data updated successfully": "User data updated successfully",
          "Fields cannot be empty": "Fields cannot be empty",
          "Password must be at least 6 characters":
              "Password must be at least 6 characters"
        }
      };
}
